---
output:
  html_document: default
  pdf_document: default
---


# Lernen mit Paulus zu beten.  Kolosser 1.1-14 {#teil_01_1_14}

```{block, type='rmdquote'}
1 Paulus, Apostel Jesu Christi durch den Willen Gottes, und der Bruder Timotheus 2 an die heiligen und treuen Brüder in Christus in Kolossä: Gnade sei mit euch und Friede von Gott, unserem Vater, und dem Herrn Jesus Christus!
Das Gebet des Apostels für die Gemeinde
3 Wir danken dem Gott und Vater unseres Herrn Jesus Christus, indem wir allezeit für euch beten, 4 da wir gehört haben von eurem Glauben an Christus Jesus und von eurer Liebe zu allen Heiligen, 5 um der Hoffnung willen, die euch aufbewahrt ist im Himmel, von der ihr zuvor gehört habt durch das Wort der Wahrheit des Evangeliums, 6 das zu euch gekommen ist, wie es auch in der ganzen Welt [ist] und Frucht bringt, so wie auch in euch, von dem Tag an, da ihr von der Gnade Gottes gehört und sie in Wahrheit erkannt habt. 7 So habt ihr es ja auch gelernt von Epaphras, unserem geliebten Mitknecht, der ein treuer Diener des Christus für euch ist, 8 der uns auch von eurer Liebe im Geist berichtet hat.
9 Deshalb hören wir auch seit dem Tag, da wir es vernommen haben, nicht auf, für euch zu beten und zu bitten, dass ihr erfüllt werdet mit der Erkenntnis seines Willens in aller geistlichen Weisheit und Einsicht, 10 damit ihr des Herrn würdig wandelt und ihm in allem wohlgefällig seid: in jedem guten Werk fruchtbar und in der Erkenntnis Gottes wachsend, 11 mit aller Kraft gestärkt gemäß der Macht seiner Herrlichkeit zu allem standhaften Ausharren und aller Langmut, mit Freuden, 12 indem ihr dem Vater Dank sagt, der uns tüchtig gemacht hat, teilzuhaben am Erbe der Heiligen im Licht. 13 Er hat uns errettet aus der Herrschaft der Finsternis und hat uns versetzt in das Reich des Sohnes seiner Liebe, 14 in dem wir die Erlösung haben durch sein Blut, die Vergebung der Sünden. 

-- Kolosser 1.1-14
```

## Gruss des Paulus an die Kolosser (Kolosser 1.1-2)

<!--
> 1 Paulus, Apostel Jesu Christi durch den Willen Gottes, und der Bruder Timotheus 2 an die heiligen und treuen Brüder in Christus in Kolossä: Gnade sei mit euch und Friede von Gott, unserem Vater, und dem Herrn Jesus Christus! 
-->


### "Paulus, Apostel Jesu Christi..."

Damals gab es kein neues Testament. Die damaligen Christen waren auf mündliche 
Überlieferungen angewiesen. Indem Paulus sich als Apostel Jesus Christi 
vorstellt, zeigt er eindeutig, dass er die Autorität hat, das Wort Gottes zu 
lehren, dass er im direkten Auftrag von Jesus diesen Brief schreibt. 
Gott hat nämlich Paulus "vom Mutterleib an ausgesondert" (Galater 1.15) 
und Paulus wurde von Jesus selber berufen Apostel zu werden (Apostelgeschichte 9:15-16). Das Evangelium,
was Paulus verkündigt, hat Paulus direkt vom Jesus Christus erhalten (Galater 1.11-12)

Paulus hat deshalb heute die gleiche Autorität wie damals.

### "...an die heiligen und treuen Brüder in Christus in Kolossä..."

Wieso nennt Paulus die Christen in Kolossä "Heilige" und Brüder?

Paulus nennt sie Heilige, weil Jesus an ihre Stelle für ihre Sünden mit seinem 
Blut bestraft wurde (die "Erlösung durch [das] Blut" Jesus, v. 14):


```{block, type='rmdquote'}
Auch euch, die ihr einst entfremdet und feindlich gesinnt wart in den bösen Werken, hat er jetzt versöhnt in dem Leib seines Fleisches durch den Tod, um euch heilig und tadellos und unverklagbar darzustellen vor seinem Angesicht

-- Kolosser 1.21-22
```


      
D.h. wir haben eine neue Identität in Christus (und wir sollten danach leben). Bist du keine Heiliger, wirst du nie Gott sehen (Hebräer 12.14)

Paulus nennt die Kolosser Brüder (Geschwister), weil Jesus uns, Christen, durch sein Opfer mit Gott dem Vater versöhnt hat, so dass wir Kinder Gottes sind (Römer 8.14-17, Galater 4.4-7). Wir sind eine Familie! Paulus kannte die Kolosser nicht und nahm sie als Brüder wahr und setzte sich voll ein, indem er für sie betete und sie durch seinen Brief lehrte.

```{block, type='rmdquestion'}
Ist dir bewusst, dass du ein Heiliger bist? Dass wir Geschwister sind? Wie siehst du die andere Christen? Die, die du nicht kennst? Als Geschwister? Siehst du das Blut Jesus, das uns verbindet?
```


<!-- Was meint Paulus: "Gnade sei mit euch und Friede von Gott" -->

### "...Gnade und Friede von Gott, unserem Vater, und dem Herrn Jesus Christus!"

Wünscht Paulus den Kolosser Gnade und Friede von Gott, *seinem* Vater und *seinem Freund* Jesus Christus?

Wir sollen eine persönliche Beziehung zu Gott haben, eine Vater-Kind Beziehung (Galater 4.4-7). Leider sind wir und unsere Gesellschaft vom Individualismus zu stark geprägt. Individualismus ist kein christlicher Wert (Johannes 17.20-23). Gott ist aber Gott ist kein individueller Gott. Er ist der Gott von Abraham, Isaak, Jakob, ... Er ist nicht nur dein Vater, sondern *unserem* Vater. Du bist ein Teil des Körpers Christi. Unsere Beziehung zu Gott ist eng mit unserem Beziehung zu unseren Mitchristen gekoppelt. Wer Gott liebt, liebt die Anderen. Es gibt kein Solo-Christen (1. Johannes 4.7-21)

Paulus nennt Jesus "Herr". Da sollst du kurz über die Bedeutung vom Wort "Herr" nachdenken. Es geht um Gehorsamkeit gegenüber dem Boss oder dem Chef. Hier stellt sich Paulus als Sklave, Diener, Knecht Jesus vor. D.h. er verzichtet freiwillig auf seine Freiheit. Diese Art Sklaverei ist eigentlich das Beste was man haben kann, denn das Joch Jesus ist sanft (Matthäus 11.29-30).

Paulus nennt Jesus Christus der Messias. Der ersehnte Retter, die Erfüllung des Versprechens Gottes an Adam und Eva, an Abraham, etc., der rote Faden, welcher sich durch die Bibel zieht.


```{block, type='rmdquestion'}
Wie siehst du Gott? Jesus? Wie nimmst du beide wahr? Wie haben sich unser Gott und unser Herr offenbart?
```


## Paul dankt Gott für die Kolosser für ihren Glauben und Liebe (Kolosser 1.3-8)

<!--
> 3 Wir danken dem Gott und Vater unseres Herrn Jesus Christus, indem wir allezeit für euch beten, 4 da wir gehört haben von eurem Glauben an Christus Jesus und von eurer Liebe zu allen Heiligen, 5 um der Hoffnung willen, die euch aufbewahrt ist im Himmel, von der ihr zuvor gehört habt durch das Wort der Wahrheit des Evangeliums, 6 das zu euch gekommen ist, wie es auch in der ganzen Welt [ist] und Frucht bringt, so wie auch in euch, von dem Tag an, da ihr von der Gnade Gottes gehört und sie in Wahrheit erkannt habt. 7 So habt ihr es ja auch gelernt von Epaphras, unserem geliebten Mitknecht, der ein treuer Diener des Christus für euch ist, 8 der uns auch von eurer Liebe im Geist berichtet hat.
-->

### "Wir danken dem Gott und Vater unseres Herrn Jesus Christus indem wir allezeit für euch beten"

Wem Paulus dankt? Gott unserem Vater

```{block, type='rmddefinition'}
 **Das biblische Gebetsmodell**

Zum unserem Vater beten in Name Jesus durch den Geist.

So hat sich Gott offenbart.

```

Wiederum sagt Paulus "unseres" Herrn und nicht "meines Herrn". 

Gott danken, dass ist Gott loben und ehren: 

- Man zeigt unsere Abhängigkeit zu Gott, man bezeugt, dass die Hand Gottes am wirken ist. 
- Man freut sich an das Wirken Gottes, das gefällt Gott.
- Danken ist der Schlüssel zu Zufriedenheit, eine Perspektivänderung

Danken ist deswegen ein zentrales Element des Gebetes: 

```{block, type='rmdquote'}
in allem lasst durch Gebet und Flehen mit Danksagung eure Anliegen vor Gott kundwerden

-- Philipper 4.6
```


Paulus dankt erst (siehe auch 1. Korinther 1.4) bevor er ein Paar Verse später Gott, um etwas bittet. Ausser in Galater und Titus dankt Paulus Gott in all seinen Briefe.

```{block, type='rmdquestion'}
Betest du zu Gott dem Vater? Wenn du betest, wie viel Platz nimmt dein Dank an Gott?
```

### "...da wir gehört haben von eurem Glauben an Jesus Christus und von eurer Liebe zu allen Heiligen..."

Wieso dankt Paulus Gott anstatt den Kolosser für ihre Bemühungen zu danken bzw. zu loben oder ermutigen?

Paulus dankt Gott dafür, dass seine Gnade im Leben der Kolosser wirksam wird. Die Betonung liegt eindeutig auf die Wirkung Gottes. Gott ist souverän. Mann vergisst schnell, dass es Gott ist, der in uns das "Wollen sowie das Vollbringen" (Philipper 2.13) wirkt, ohne dass wir uns aus unserer Verantwortung entziehen können. Allein schaffen wir nicht, Gott zu gefallen. Die Gnade Gottes ist unsere "juristische" Heiligung (wir sind heilig vor Gott) sowie unsere praktische Heiligung im Alltag (wir handeln wie Heiligen, d.h., wir sündigen nicht). Wie genau es funktioniert, ist ein Geheimnis. 

Wie häufig dankt Paulus Gott für die Auswirkung der Gnade Gottes bei den Kolosser?

"Allezeit"! Das zeigt, dass man nicht aufhören sollte, dafür zu danken.
      

```{block, type='rmddefinition'}
Zwei Wahrheiten, die in der Bibel enthalten sind:

1. Gott ist absolut souverän, aber seine Souveränität wirkt nie so, dass die
Verantwortung des Menschen verringert wird.
2. Der Mensch ist verantwortlich und wird sich für sein Handeln verantworten müssen.
Aber die menschliche Verantwortung schwächt niemals die Souveränität Gottes.      
```

Was sind Glauben und Liebe zu den Heiligen?

Glauben und Liebe sind keine abstrakten Begriffe. Damit man berichten kann, dass die Kolosser Glaube und Liebe haben, müssen Ihre Glaube und Liebe sichtbar sein, ein öffentliche Wirkung haben.

Der Glaube ist "eine feste Zuversicht auf das, was man hofft, eine Überzeugung von Tatsachen, die man nicht sieht" (Hebräer 11.1). 
<!-- Man bleibt tief gewurzelt im Wort Gottes und passt sich den Gedanken unserer Welt nicht an (Römer 12.2) -->
Wenn man in Hebräer 11 weiter liest, entdeckt man der Glauben der Helden des AT. Was stellt man fest? Der Glaube bewirkt gute Werke, die Gott gefallen. Das ist genau was Jakobus sagt: "Denn gleichwie der Leib ohne Geist tot ist, also ist auch der Glaube ohne die Werke tot" (Jakobus 2.26). Hier sieht man die Beziehung zwischen Glaube und Liebe. Die Liebe ist der Prüfstein des Glaubens. Keine Liebe, keine Glaube. 

Wer sind die Heiligen? 

Mit Heiligen sind die Christen in dem Umkreis der Kolosser gemeint. Die Liebe zu unseren Geschwistern sollte unser Markenzeichen sein: In Johannes 13.35 sagt Jesus, dass "jedermann [wird] erkennen, dass ihr meine Jünger seid, wenn ihr Liebe untereinander habt". Wie drück sich die Liebe aus? Zwei Beispiele

```{block, type='rmdquote'}
Wir ermahnen euch aber, Brüder: Verwarnt die Unordentlichen, tröstet die Kleinmütigen, nehmt euch der Schwachen an, seid langmütig gegen jedermann! 15 Seht darauf, dass niemand Böses mit Bösem vergilt, sondern trachtet allezeit nach dem Guten, sowohl untereinander als auch gegenüber jedermann!

-- 1. Thessalonicher 5.14-15
```

```{block, type='rmdquote'}
Die Liebe ist langmütig und gütig, die Liebe beneidet nicht, die Liebe prahlt nicht, sie bläht sich nicht auf; 5 sie ist nicht unanständig, sie sucht nicht das Ihre, sie läßt sich nicht erbittern, sie rechnet das Böse nicht zu; 6 sie freut sich nicht an der Ungerechtigkeit, sie freut sich aber an der Wahrheit; 7 sie erträgt alles, sie glaubt alles, sie hofft alles, sie erduldet alles.

-- 1. Korinther 13.4-7
```


```{block, type='rmdquestion'}
Wie oft dankst du Gott für deine Geschwister? Dass Gott in sie wirkt? Wie oft dankst du Gott für materielle Sachen, die für die Ewigkeit nichts bringen.

Bewirkt dein Glaube Taten? Spürt man hier in unserer Gemeinde unsere gegenseitige Liebe? Ist es hier in der Gemeinde anders als in der Welt?
```


### "… um der Hoffnung willen, die euch aufbewahrt ist im Himmel, von der ihr zuvor gehört habt durch das Wort der Wahrheit des Evangeliums"

Was ist diese Hoffnung wovon Paulus redet? 

Vers 12 liefert die Erklärung: die Hoffnung an die Teilhabe am "Erbe der Heiligen im Licht". Was heisst das konkret? Kinder Gottes (Christen) sind "Erben Gottes und Miterben des Christus" und werden "mit ihm verherrlicht werden" (Römer 8.17). Wir haben einen Schatz, eine Erbe im Himmel! Paulus sagte: "die Leiden der jetzigen Zeit [fallen] nicht ins Gewicht [...] gegenüber der Herrlichkeit, die an uns geoffenbart werden soll." (Römer 8.18)


Was ist die Verbindung zwischen dieser Hoffnung und dem Glaubem und der Liebe?

Die Hoffnung ist der Antrieb unseres Glaubens und unserer Liebe. Wir haben eine gemeinsame Hoffnung. Wir sind als Geschwister gemeinsam unterwegs zu Gottes Haus und wir unterstützen uns auf dem Weg, dass wir alle zusammen ankommen.


Wo liegt diese Hoffnung? 

Diese Hoffnung liegt im Himmel aufbewahrt. Niemand kann uns diese Hoffnung wegnehmen. Diese Hoffnung ändert unseren Blickwinkel. Wir schauen zum Himmel und  nicht mehr auf diese Welt und ihre Probleme.


Woher haben die Kolosser von dieser Hoffnung erfahren? 

Im Evangelium, das ihnen von Epaphras verkündigt wurde. Wir alle wissen, wie schnell wir unsere Hoffnung auf den Himmel verlieren oder vergessen... deshalb, kann es uns nur gut tun, sich von dem Evangelium zu ernähren, weil es eine Kraft ist!
 
```{block, type='rmdquestion'}    
Lebst du im Alltag in dieser Hoffnung? Was bewirkt diese Hoffnung bei dir?
```

### "...das Wort der Wahrheit des Evangeliums, das zu euch gekommen ist, wie es auch in der ganzen Welt [ist] und Frucht bringt, so wie auch in euch, von dem Tag an, da ihr von der Gnade Gottes gehört und sie in Wahrheit erkannt habt."

Was ist das Evangelium?

Das **Evangelium** ist die gute Nachricht. Damals, als es noch kein neues Testament gab, waren die Apostel und ihre Mitarbeiter die Träger des Evangeliums.
In unserer postmoderne Welt ist die Wahrheit relativ. Das Evangelium ist aber ein **Wort der Wahrheit**, woran man sich orientieren kann.
Das Evangelium ist eine Kraft, die in den Menschen wirkt und Früchte trägt. Diese Kraft ist weder magisch noch von uns beherrschbar. Das ist der Samen, der auf die gute Erde fällt und Früchte trägt (Markus 4.8). Die Früchte, die Paulus erwähnt, sind u.a. der Glaube, die Liebe und die Hoffnung. Gott wirkt durch sein Wort.
      
Was meint Paulus mit dem Ausdruck "das Evangelium, das in der ganzen Welt ist und Früchte bringt"?

Das kann eine Anspielung an den ursprünglichen Plan Gottes sein. Bei der Schöpfung befahl Gott den Menschen fruchtbar zu sein, sich zu mehren und die Erde zu füllen (1. Mose 1.26-28). Die Erde soll gefüllt werden mit Menschen nach dem Bild Gottes. Als Adam und Eva gegen Gott rebellierten, drangen Sünde und Tod ein und verwüsteten die Welt Gottes. Durch das Evangelium erschafft Gott jedoch ein Volk von Ebenbildern (siehe auch Kolosser 3.9-10):

```{block, type='rmdquote'}
Denn die er zuvor ersehen hat, die hat er auch vorherbestimmt, dem Ebenbild seines Sohnes gleichgestaltet zu werden, damit er der Erstgeborene sei unter vielen Brüdern.

-- Römer 8.29
```

Das ist der Rettungsplan Gottes, er stellt seinen Plan wieder her. Er verwandelt uns wieder in das, was wir hätten sein sollen.


### "...So habt ihr es ja auch gelernt von Epaphras, unserem geliebten Mitknecht, der ein treuer Diener des Christus für euch ist, 8der uns auch von eurer Liebe im Geist berichtet hat."


W as ist ein treuer Diener des Christus?

```{block, type='rmdquote'}
Epaphras, der einer der Euren ist, ein Knecht des Christus, der allezeit in den Gebeten für euch kämpft, damit ihr fest steht, vollkommen und zur Fülle gebracht in allem, was der Wille Gottes ist.
    
-- Kolosser 4.12
```

```{block, type='rmdquestion'}    
Bist du ein treuer Diener von Jesus? Kämpfst du für uns, indem du betest, dass wir Gott ähnlicher werden?
```


## Paul bittet für die Kolosser  (Kolosser 1.9-10)

### "Deshalb hören wir auch seit dem Tag, da wir es vernommen haben, nicht auf, für euch zu beten und zu bitten..."

Jetzt ist es spannend. Nachdem Paulus Gott gedankt hat, bittet er für die Kolosser. Wofür? 

Dass sie "mit der Erkenntnis seines Willens in aller geistlichen Weisheit und Einsicht [erfüllt werden]".

Wieso "deshalb"? 

Bei Paulus sind Gebetsanliegen und Bitte eng verbunden. Wir haben eher die Tendenz zu danken, wenn alles gut geht und zu bitten, wenn es uns schlecht geht. Paulus nicht! Wenn Paulus Gott dafür dankt, dass die Gnade Gottes in uns wirksam wird, bittet er anschliessend, dass die Gottes Gnade noch mehr wirkt. Hier kann man ein Parallel zum Wort Jesu sehen. In Johannes 15.2 sagt Jesus: "Jede [Rebe] aber, die Früchte bringt, reinigt [Gott der Vater], damit sie mehr Frucht bringt."
Paulus dankt für die Früchte, die die Reben bringen und bittet dafür, dass sie mehr Früchte bringen.


Wie oft betet Paulus? 

Er hört nicht auf, für die Kolosser zu bitten, dass sie erfüllt werden mit der Erkenntnis des Willens Gottes. Das zeigt, dass es Sachen gibt, wofür man nicht aufhören sollte zu beten! Sogar für Geschwister, die man nie gesehen hat.

```{block, type='rmdquestion'}    
Bitten wir Gott häufiger, wenn die Gemeinde Schwierigkeiten hat oder wenn sie wächst?

Bitten wir Gott regelmässig, dass seine Gnade mehr in unserem Leben einwirkt?
```
     
### "und zu bitten, dass ihr erfüllt werdet mit der Erkenntnis seines Willens in aller geistlichen Weisheit und Einsicht, ..."

Was ist die Erkenntnis seines Willens?

Es geht nicht in erste Linie, um die unzähligen alltags Entscheidungen, wie "wie soll ich mich heute anziehen" , "wen soll ich heiraten", "welcher Job soll ich nehmen". Hier meine ich nicht, dass diese Frage unwichtig sein. Sondern es gibt etwas noch essenzieller!

Es geht auch nicht, um ein theoretisches gesammeltes Wissen. Die Pharisäer kannten irgendwie sehr gut die Schriften ohne zu sehen, dass die Schrift von Jesus bezeugte! Jesus sagte Ihnen "Ihr erforscht die Schriften, weil ihr meint, in ihnen das ewige Leben zu haben; und sie sind es, die von mir Zeugnis geben. 40 Und doch wollt ihr nicht zu mir kommen, um das Leben zu empfangen." (Johannes 5.39-40)

"Die Erkenntnis seines Willens" ist etwas tieferes. Es geht um unsere Grundgedanken, unsere Grundhaltung. Hier ist ein tiefer Verständnis der Offenbarung Christus und all was er bedeutet für uns und das Universum gemeint. Denn in Christus sind «alle Schätze der Weisheit und der Erkenntnis verborgen» (Kolosser 2.3).

Was ist der Wille Gottes?

- Heiligung (1. Thessalonicher 4.3)
- Dankbare Freude: «Freut euch allezeit!, Betet ohne Unterlass! Seid in allem dankbar; denn das ist der Wille Gottes in Christus Jesus für euch» (1. Thessalonicher 5.16-18)
-Es geht darum, im Einklang mit unseren neuen Identität zu leben. Das wird betont durch die Referenz zu "aller geislichen Weisheit und Einsicht". Die Erkenntnis des Willens Gottes besteht aus Weisheit (wie soll man leben) und Einsicht. Das richtige Handel ist gefordert. Das ist lebenswichtig weil:
"Nicht jeder, der zu mir sagt: Herr, Herr! wird in das Reich der Himmel eingehen, sondern wer den Willen meines Vaters im Himmel tut" (Matthäus 7.21)

Wiederum, Paul betet dass Gott den Kolossär mit der Erkenntnis seines Willens erfüllt werden. Gott kann uns diese Erkenntnis schenken gleichzeitig sollen wir uns danach sehnen, nach Gottes Willen zu leben. D.h. auch Gott dafür beten, dass er uns mit der Erkenntnis seines Willens efüllt. Denn wir können von uns selbst Gott nicht kennen. Er offenbart sich uns und deshalb bittet Paulus darum!
     

```{block, type='rmdquestion'}    
Bitten wir, dass Gott uns mit der Erkenntnis seines Willens efüllt?
```     
     

Was ist das wichtigste für die Gemeinde? Evangelisation? Gebet? Seelsorge? Theologie?

```{block, type='rmdquote'}
In der biblischen Sicht bringt eine tiefere Gotteskenntnis eine massive Verbesserung in den anderen genannten Bereichen mit sich: Reinheit, Integrität, evangelistische Wirksamkeit, besseres Schriftstudium, verbesserte persönliche und gemeinsame Anbetung und vieles mehr. 
Aber wenn wir diese Dinge suchen, ohne leidenschaftlich nach einer tieferen Kenntnis von Gott zu streben, laufen wir egoistisch nach Gottes Segen, ohne ihm nachzulaufen.
Wir sind noch schlimmer als der Mann, der die Dienste seiner Frau will - jemand, zu dem er nach Hause kommen soll, jemand, der kocht und putzt, jemand, mit dem er schlafen kann -, ohne sich jemals wirklich zu bemühen, seine Frau zu kennen und zu lieben und zu entdecken, was sie will und braucht; 
Wir sind schlimmer als ein solcher Mann, sage ich, denn Gott ist mehr als jede Frau, mehr als die besten Frauen: Er ist vollkommen in seiner Liebe, er hat uns für sich selbst gemacht, und wir sind ihm gegenüber verantwortlich. 
    
-- D.A. Carson, Praying With Paul: A Call to Spiritual Reformation (2nd ed.)
```


```{block, type='rmdquestion'}    
Beten wir für das wichtigste? Gott besser kennen, seinen Willen besser kennen, seine Worte in unsere Herzen tragen (d.h. danach handeln).
```     
     
### "... damit ihr des Herrn würdig wandelt und ihm in allem wohlgefällig seid..."

Wofür sollen wir erfüllt mit der Erkenntnis Gottes? Was ist das Ziel?

Wie der echte Glaube gute Werke bewirkt, bewirkt die Erkenntnis Gottes ein Verhalten, das Gott gefällt. Damit sein Leser verstehen, was "Des Herrn würdig wandelt" heisst, schreibt Paulus dazu: Gott "ihm in allem wohlgefällig sein". 

In Philipper 4.8 gibt Paulus mehr Details über was Gott gefällt:
"Im Übrigen, ihr Brüder, alles, was wahrhaftig, was ehrbar, was gerecht, was rein, was liebenswert, was wohllautend, was irgendeine Tugend oder etwas Lobenswertes ist, darauf seid bedacht!"

Es geht mehr als nur "nicht böses tun". Es geht darum, aktiv zu versuchem, Gott zu gefallen, d.h. die gute Taten zu suchen. Und eigentlich solltes es uns leicht fallen, denn wir sind "erschaffen in Christus Jesus zu guten Werken, die Gott zuvor bereitet hat, damit wir in ihnen wandeln sollen" (Epheser 2.10).  


In allem was wir machen, sollen wir uns fragen: gefällt es Gott? Wir sind hier nicht mehr in einer gesetzliche Logik ("du musst", "du darfst nicht") sondern in eine Logik der Liebe, der Freude. Diese Logik der Liebe war von Anfang an, der Charakter der Beziehung zu Gott, auch im alten Testament (z.B. Micha 6.6-8). "Gott wohlgefällig sein" bedeutet Gott Freude machen, d.h. ihn durch unser Wandeln, unsere Taten zu loben.


## Paulus zeigt die Eigenschaften eines Lebens, das Gott gefällt.

### "... in jedem guten Werk fruchtbar..."

"Denn wir sind seine Schöpfung, erschaffen in Christus Jesus zu guten Werken, die Gott zuvor bereitet hat, damit wir in ihnen wandeln sollen." Epheser 2.10

Wichtig ist Früchte zu tragen. Wieviel ist Personabhängig, wie es im Gleichnis vom Säman geschrieben steht: "Und anderes fiel auf das gute Erdreich und brachte Frucht, die aufwuchs und zunahm; und etliches trug dreißigfältig, etliches sechzigfältig und etliches hundertfältig." Markus 4.8

### "... und in der Erkenntnis Gottes wachsend..."

Ist es nicht komisch? Wenn man mit der Erkenntnis des Willens Gottes erfüllt ist, wächst man in der Erkenntnis Gottes! Der Kreis ist geschlossen!

Eins ist klar: wir werden auf der Erde nie Gott genug kennen. Wir haben ein grosses Wachstum Potenzial. Wenn man erfüllt mit der Erkenntnis des Willens Gottes, weiss man, was für einen Schatz dieser Erkenntnis ist. Und das motiviert, Gott noch besser zu kennen. Das ist ein Positiver Kreis


### "... mit aller Kraft gestärkt gemäß der Macht seiner Herrlichkeit zu allem standhaften Ausharren und aller Langmut, mit Freuden..."

Die Kraft Gottes ist unglaubig. Der Grösste Ausdruck seiner Kraft ist die Auferstehung Jesus, der Sieg über dem Tod, der Sünde und über Satan. 

Wie drückt sich die Kraft Gottes in seinen Kindern aus?

Nicht in erste Linie durch Wundern sondern indem man standhaft ausharrt, indem man langmütig ist. Glauben trozt den Schwierigkeiten und Verfolgungen, Freude an Gott behalten. Wir fallen hin, stehen wieder auf. Das bringt uns zu der letzten Eigenschaft...


### "... indem ihr dem Vater Dank sagt, der uns tüchtig gemacht hat, teilzuhaben am Erbe der Heiligen im Licht."

Was ist dankbarkeit?

Dankbarkeit ist die Antwort auf die Gnade. Wer keine Dankbarkeit aufweist, hat die Gnade Gottes nicht erlebt bzw. verstanden (siehe das Gleichnis vom unbarmherzigen Knecht in Matthäus 18.23-35). Gott danken ist vielleicht der erste Schritt eines Lebens, das Gott gefällt. Gott danken für was er für uns gemacht, das ist ihn anzuerkennen, für was er ist, unsere Abhängigkeit von Ihm auszudrücken. Das ist Gott loben und anbeten.

Und was hat Gott für uns gemacht?

- Er schenkt uns die Teilhabe "am Erbe der Heiligen im Licht" (Kolosser 1.12). Hier benutzt Paulus den Wortschatz vom 5. Mose 10.9 bezüglich der Leviten, dieser Stamm den Gott für sich selbst beanspruchte: "Darum hat Levi weder Anteil noch Erbe mit seinen Brüdern; denn der Herr ist ihr Erbteil, wie der Herr, dein Gott, es ihm verheissen hat". Paulus könnte andeuten, dass die Kolosser die neuen Leviten sind, ausgesondert für den Dienst Gottes (siehe auch 1. Petrus 2.9-10)!
- "Er hat uns errettet aus der Herrschaft der Finsternis und hat uns versetzt in das Reich des Sohnes seiner Liebe, 14 in dem wir die Erlösung haben durch sein Blut, die Vergebung der Sünden." Kolosser 1.13-14 Das ist eine mögliche Anspielung an die Erretung von Israel aus Egypten.

Und somit haben wir mehr als alles bekommen! Wenn wir öfter davon bewusst würden, würde unser Leben anders aussehen!


## Zusammenfassung

Was können wir von Paulus Gebet lernen?

Er betet reglemässig, ständig… für die Einwirkung der Gnade Gottes in das Leben der Kolosser

```{block, type='rmdquestion'}    
Wie ist unser Gebetsleben?
```    

Er bedankt Gott, für den Glaube und die Liebe der Kolosser.

```{block, type='rmdquestion'}    
Wie oft danken wir Gott für sein Wirken in unseren Geschwistern? 

Sind wir dankbar in unseren Gebeten?
```  

Er verbindet Dank und Bitte.

```{block, type='rmdquestion'}    
Verbinden wir Dank und Bitte?
``` 

Er bittet Gott um das wichtigste für die Kolosser, nämlich, dass die Kolosser mit der Erkenntnis seines Willens erfüllt werden.

```{block, type='rmdquestion'}    
Beten wir für das wichtigste? 

Sehnen wir uns nach einer tieferen Kenntnis des Willens Gottes? Eine Erkenntnis, die uns ändert?
```
    
Er erklärt den Kolosser, das Ziel dieses Bitte: er möchte, dass sie ein Leben führen, das Gott gefällt.

```{block, type='rmdquestion'}    
Sind wir vom Plan Gottes bewusst? Wofür er uns hat gerettet?

Wollen wir ein Leben führen, das Gott gefällt?
```



Die Erkenntnis des Willens Gottes, Gott besser kennen. Das ist der Schlüssel, damit unser Leben Gott wohlgefällt.


Wer Jesus kennt, kennt der Vater. Deshalb ist es wichtig, ein gutes Verständnis der Person Jesus, seiner Herrlichkeit und seines Erlösungswerks zu haben. In nächsten Abschnitt liefert Paulus eine starke Beschreibung von Jesus, bekannt als der Psalm-Jesus (Kolosser 1.15-20). 

