---
output:
  html_document: default
  pdf_document: default
---


# Jesus, der Sohn Gottes, Herr über Alles.  Kolosser 1.15-23 {#teil_02}

```{block, type='rmdquote'}
15 Dieser ist das Ebenbild des unsichtbaren Gottes, der Erstgeborene, der über aller Schöpfung ist. 16 Denn in ihm ist alles erschaffen worden, was im Himmel und was auf Erden ist, das Sichtbare und das Unsichtbare, seien es Throne oder Herrschaften oder Fürstentümer oder Gewalten: alles ist durch ihn und für ihn geschaffen; 17 und er ist vor allem, und alles hat seinen Bestand in ihm.

18 Und er ist das Haupt des Leibes, der Gemeinde, er, der der Anfang ist, der Erstgeborene aus den Toten, damit er in allem der Erste sei. 19 Denn es gefiel [Gott], in ihm alle Fülle wohnen zu lassen 20 und durch ihn alles mit sich selbst zu versöhnen, indem er Frieden machte durch das Blut seines Kreuzes – durch ihn, sowohl was auf Erden als auch was im Himmel ist.

21 Auch euch, die ihr einst entfremdet und feindlich gesinnt wart in den bösen Werken, hat er jetzt versöhnt 22 in dem Leib seines Fleisches durch den Tod, um euch heilig und tadellos und unverklagbar darzustellen vor seinem Angesicht, 23 wenn ihr nämlich im Glauben gegründet und fest bleibt und euch nicht abbringen laßt von der Hoffnung des Evangeliums, das ihr gehört habt, das verkündigt worden ist in der ganzen Schöpfung, die unter dem Himmel ist, und dessen Diener ich, Paulus, geworden bin.  

-- Kolosser 1.15-23
```

## Die Vorherrschaft Jesus über die ganze Schöpfung (Kolosser 1.15-17)

<!--
> 1 Paulus, Apostel Jesu Christi durch den Willen Gottes, und der Bruder Timotheus 2 an die heiligen und treuen Brüder in Christus in Kolossä: Gnade sei mit euch und Friede von Gott, unserem Vater, und dem Herrn Jesus Christus! 
-->


### "Dieser ist das Ebenbild des unsichtbaren Gottes, der Erstgeborene, der über aller Schöpfung ist...."

Gott ist unsichtbar, keiner kann ihn sehen:
"Niemand hat Gott je gesehen» schreibt Johannes (1,18)"

Was ist das erste Gebot von den Zehn Gebote?

"Du sollst dir kein Bildnis noch irgend ein Gleichnis machen, weder von dem, was oben im Himmel, noch von dem, was unten auf Erden, noch von dem, was in den Wassern, unter der Erde ist."

Jesus ist das Bild Gottes, das einzige richtige Bild Gottes, das einzige Bild, das wie anbeten dürfen. Weil Jesus Gott der Sohn ist!

"Dieser ist der wahrhaftige Gott und das ewige Leben." 1. Johannes 5.20

Philippus sagte Jesus: "Herr, zeige uns den Vater, so genügt es uns! Was war die Antwort Jesu?

"Wer mich gesehen hat, der hat den Vater gesehen."
      
Gott der Vater hat sich uns durch Gott den Sohn offenbart.
